// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[jenis]/[tahun]/[nomor]/[partial-bab].tsx";
import * as $1 from "./routes/[jenis]/[tahun]/[nomor]/[partial-buku].tsx";
import * as $2 from "./routes/[jenis]/[tahun]/[nomor]/[partial-pasal].tsx";
import * as $3 from "./routes/[jenis]/[tahun]/[nomor]/[partial].tsx";
import * as $4 from "./routes/[jenis]/[tahun]/[nomor]/image.png.tsx";
import * as $5 from "./routes/[jenis]/[tahun]/[nomor]/index.ts";
import * as $6 from "./routes/[jenis]/[tahun]/[nomor]/info.tsx";
import * as $7 from "./routes/[jenis]/[tahun]/[nomor]/isi.tsx";
import * as $8 from "./routes/[jenis]/[tahun]/[nomor]/kerangka.tsx";
import * as $9 from "./routes/[jenis]/[tahun]/[nomor]/terkait.tsx";
import * as $10 from "./routes/[jenis]/[tahun]/index.tsx";
import * as $11 from "./routes/[jenis]/index.tsx";
import * as $12 from "./routes/_404.tsx";
import * as $13 from "./routes/_500.tsx";
import * as $14 from "./routes/_app.tsx";
import * as $15 from "./routes/_middleware.tsx";
import * as $16 from "./routes/api/autocomplete.ts";
import * as $17 from "./routes/atom.xml.ts";
import * as $18 from "./routes/feed.json.ts";
import * as $19 from "./routes/index.tsx";
import * as $20 from "./routes/rss.xml.ts";
import * as $21 from "./routes/search.tsx";
import * as $22 from "./routes/sitemap-[jenis]-[tahun].xml.ts";
import * as $23 from "./routes/sitemap-[jenis].xml.ts";
import * as $24 from "./routes/terbaru.tsx";
import * as $$0 from "./islands/dark_mode_toggler.tsx";
import * as $$1 from "./islands/print_button.tsx";
import * as $$2 from "./islands/search_input.tsx";
import * as $$3 from "./islands/web_share_button.tsx";
import * as $$4 from "./islands/webmentions.tsx";

const manifest = {
  routes: {
    "./routes/[jenis]/[tahun]/[nomor]/[partial-bab].tsx": $0,
    "./routes/[jenis]/[tahun]/[nomor]/[partial-buku].tsx": $1,
    "./routes/[jenis]/[tahun]/[nomor]/[partial-pasal].tsx": $2,
    "./routes/[jenis]/[tahun]/[nomor]/[partial].tsx": $3,
    "./routes/[jenis]/[tahun]/[nomor]/image.png.tsx": $4,
    "./routes/[jenis]/[tahun]/[nomor]/index.ts": $5,
    "./routes/[jenis]/[tahun]/[nomor]/info.tsx": $6,
    "./routes/[jenis]/[tahun]/[nomor]/isi.tsx": $7,
    "./routes/[jenis]/[tahun]/[nomor]/kerangka.tsx": $8,
    "./routes/[jenis]/[tahun]/[nomor]/terkait.tsx": $9,
    "./routes/[jenis]/[tahun]/index.tsx": $10,
    "./routes/[jenis]/index.tsx": $11,
    "./routes/_404.tsx": $12,
    "./routes/_500.tsx": $13,
    "./routes/_app.tsx": $14,
    "./routes/_middleware.tsx": $15,
    "./routes/api/autocomplete.ts": $16,
    "./routes/atom.xml.ts": $17,
    "./routes/feed.json.ts": $18,
    "./routes/index.tsx": $19,
    "./routes/rss.xml.ts": $20,
    "./routes/search.tsx": $21,
    "./routes/sitemap-[jenis]-[tahun].xml.ts": $22,
    "./routes/sitemap-[jenis].xml.ts": $23,
    "./routes/terbaru.tsx": $24,
  },
  islands: {
    "./islands/dark_mode_toggler.tsx": $$0,
    "./islands/print_button.tsx": $$1,
    "./islands/search_input.tsx": $$2,
    "./islands/web_share_button.tsx": $$3,
    "./islands/webmentions.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
