name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
        - os: ubuntu-latest
          cache_path: ~/.cache/deno/
        - os: macos-latest
          cache_path: ~/Library/Caches/deno/
        - os: windows-latest
          cache_path: ~\AppData\Local\deno\

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        if: startsWith(matrix.os, 'ubuntu')
        run: deno fmt --check

      - name: Run linter
        if: startsWith(matrix.os, 'ubuntu')
        run: deno lint

      - name: Type check
        run: deno check **/*.ts **/*.tsx