name: Snapshot Workflow

on:
  push:
    branches:
      - master

jobs:
  checks:
    name: Checks Types, Linting and Formatting
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Enable pnpm
        run: |
          corepack enable pnpm
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Generate Types
        run: pnpm next typegen

      - name: Run check
        run: pnpm checks

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Enable pnpm
        run: |
          corepack enable pnpm
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --config.node-linker=hoisted

      - name: Use cache
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build step
        run: pnpm build

      - name: Copy public & static folder
        run: |
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: snapshot
          path: .next/standalone
          include-hidden-files: true

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://peraturan.info

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: snapshot

      - name: Deploy to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: ./*
          target: ${{ secrets.DEPLOY_PATH }}
